### ISSUE TITLE
Avoid redefining n()

### ISSUE THREAD

**Issue by krlmlr** [WinVector/replyr#10]
The release candidate of dplyr 0.7.5 will use the correct implementation of `n()` only if this function isn't overridden. Most likely because of this, CRAN checks of replyr fail now: https://github.com/tidyverse/dplyr/blob/master/revdep/new-problems.md#replyr

A solution seems to be to assign `dplyr::n` to the local variant of `n`, or to avoid overriding `n`.

Same problem as in https://github.com/randomchars42/bioset/issues/1.

**Comment by JohnMount** [comment]
@krlmlr , please let me know near your CRAN release time so I can push this version to CRAN.  I want to wait in case other changes are needed.

**Comment by krlmlr** [comment]
Thanks for the very quick fix. I'd like to push to CRAN as soon as possible. Usually, CRAN accepts the submission as long as we've notified all maintainers of packages we break, and it takes a few days/weeks until the update is accepted.

**Comment by JohnMount** [comment]
`replyr` `0.9.4` is now up on `CRAN` and contains the above tested fixes.
