### ISSUE TITLE
no applicable method for 'escape' applied to an object of class "lazy"

### ISSUE THREAD

**Issue by dustindall** [WinVector/replyr#2]
I tried running the following example and received the following error.

`library(sparklyr)`
`library(dplyr)`
`library(nycflights13)`
`sc   <- spark_connect(version='2.0.2', master = "local")`
`flts <- replyr::replyr_copy_to(sc, flights)`

`replyr::replyr_summary(flts, countUnique = TRUE)`

**Error in UseMethod("escape") : no applicable method for 'escape' applied to an object of class "lazy"**

I'm running spark 2.0.2 and dplyr 0.5.0.9000.

Any help will be appreciated. 

Thanks.

**Comment by dustindall** [comment]
I was working in the development version of dplyr. I moved back to dplyr 0.5 and the issues resolved.

I'm going to go ahead and close the ticket.

**Comment by JohnMount** [comment]
Thanks for the heads up- it helps me to know about this so I can check out the next version of dplyr.

**Comment by JohnMount** [comment]
dustindall, sorry you had trouble.  

From the arguments in "countUnique = TRUE" it looks like you are on CRAN version of replyr.  replyr is evolving fast (sorry!).  I see the same problem with dplyr 0.5.0.9000 and the dev version of replyr on Spark 2.0.0.

I've isolated it down to some a dplyr alone example:

```
library(sparklyr)
library(dplyr)
library(nycflights13)
sc <- spark_connect(version='2.0.0', master = "local")
flts <- replyr::replyr_copy_to(sc, flights)
flts %>% mutate(zzz=1)
```
