### ISSUE TITLE
Warnings printed - summarise_each() is deprecated

### ISSUE THREAD

**Issue by dkincaid** [WinVector/replyr#5]
When running `replyr_summary` against a Spark data frame I'm getting a bunch of warnings printed to the consoles like this:

```
`summarise_each()` is deprecated.
Use `summarise_all()`, `summarise_at()` or `summarise_if()` instead.
To map `funs` over all variables, use `summarise_all()`
```

not a major problem at all, just a small annoyance.

**Comment by JohnMount** [comment]
Sorry about the trouble.  And thanks for reporting it.

I have moved to summarize_all() in the development version of replyr.  So if you are willing to try installing that with `devtools::install_package('WinVector/replyr')` the problem should go away. I hope to send out a new release of replyr in about a week.

**Comment by dkincaid** [comment]
Thanks for fixing so quickly! I just got a chance to try it tonight and it works great.

**Comment by JohnMount** [comment]
You are very welcome.  Also `replyr` got a release- so the fix is on CRAN now.
