### ISSUE TITLE
`moveValuesToColumnsQ`: RS-DBI driver cannot retrieve result, row too big

### ISSUE THREAD

**Issue by asantucci** [WinVector/replyr#9]
Thanks for your help on the last issue re: `moveValuesToColumnsQ`, the fill-in via default values is working nicely.

When using this same function on a new table, I encounter an error.

    Error in postgresqlExecStatement(conn, statement, ...) : RS-DBI driver: (could not Retrieve the result : ERROR:  row is too big: size 10608, maximum size 8160
 
    Error in postgresqlExecStatement(conn, statement, ...) : RS-DBI driver: (could not Retrieve the result : ERROR:  relation "__asantucci___roaa15xo2kokdbdnolmp_0000000004" does not exist LINE 1: SELECT * FROM "__asantucci___roaa15xo2kokdbdnolmp_0000000004...

Do we have any idea if this issue may or may not be related to `replyr` implementation of `moveValuesToColumnsQ`? I'm not sure where the "row size" of "10,608" is coming from, as it doesn't correspond to any of the following, as far as I could tell: number of rows in my input table, number of columns in the output table, length of column names in the output table, etc.

---------------

And as a related note, I encounter the following statement printed to console each time I use `moveValuesToColumnsQ`: 

    NOTICE:  table "__asantucci___roaa15xo2kokdbdnolmp_0000000001" does not exist, skipping

What does this mean? My output looks good, so I'm scared what could be going wrong?

**Comment by JohnMount** [comment]
The "does not exist skipping" message is a bug in `RPostgreSQL`'s "drop table if exists" (the bug being that no warning should be issued if there is no table).  So that is okay- not an indication of anything wrong.

I am guessing the "maximum size 8160" is a `PostgreSQL` limitation (a combination of how many columns and what size are allowed in a result table).  Some links: https://stackoverflow.com/questions/12606842/what-is-the-maximum-number-of-columns-in-a-postgresql-select-query, http://grokbase.com/t/postgresql/pgsql-general/1034ntdbsn/error-row-is-too-big-size-8176-maximum-size-8160 .

**Comment by JohnMount** [comment]
Here is what is writing the spurious "does not exist, skipping" message to the console/std-err.

```r
reprex::reprex_info()
#> Created by the reprex package v0.1.1.9000 on 2017-11-08

# https://github.com/tidyverse/reprex/issues/90
# devtools::install_github("tidyverse/reprex")
# reprex::reprex(std_out_err = TRUE)
suppressPackageStartupMessages(library(dplyr))
packageVersion("dplyr")
#> [1] '0.7.4'
library("RPostgreSQL")
#> Loading required package: DBI
packageVersion("RPostgreSQL")
#> [1] '0.6.2'
my_db <- DBI::dbConnect(dbDriver("PostgreSQL"), 
                        host = 'localhost',
                        port = 5432,
                        user = 'postgres',
                        password = 'pg')
d <- copy_to(my_db, data.frame(x = 1), 
             name = 'd',
             overwrite = TRUE, temporary=TRUE)
```

standard output and standard error

```
#> NOTICE:  table "d" does not exist, skipping
```

**Comment by JohnMount** [comment]
Thank you very much, I really appreciate it.  I will be re-factoring `replyr` a bit soon.  In particular I may separate query generation/use from table landing.  That might (or might not) let you run the query if you are collecting results locally (which means there can't be too many rows, as you already have a lot of columns).   Also you can try to capture the query from the call and see if it works.

**Comment by JohnMount** [comment]
Just a heads-up: the pivot/un-pivot functionality is moving to cdata. This will be API breaking (sorry!).
